# Generated by Django 2.2 on 2020-01-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='termsAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
