# Generated by Django 2.2 on 2020-01-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_termsaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='termsAccepted',
        ),
    ]
